env:
  GITHUB_TOKEN: ENCRYPTED[9988534c6b59d785538492e34555a975dd712c40b69982bce538bc0ce12fd9a1c3b77b1fba663abfd1621defbfb8c821]

macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  name: build and release
  only_if: $CIRRUS_CHANGE_TITLE =~ '.*ci:release.*'
  check_clang_script:
    - clang --version
  build_release_script:
    - bash ./release-macos-arm64.sh