@echo off
chcp 65001 >NUL 2>NUL

cd /d %~dp0

call vsenv.cmd 32

@REM ==================================
@REM MSVC Major Minor Unicode version name
set BUILD_VER_MMU=32u
set BUILD_VER_MSWMMU=msw32u
set WXWIDGETS_LIBDIR=%~dp0build-wxWidgets\x86\lib\vc_dll
set wxWidgets_VERSION=3.2.1
set CMAKE_GENERATOR_PARAM=

for /F "tokens=1 delims=." %%a in ('MSBuild -nologo -version') do (
    set MSVC_TOOLSET=%%a
)
if "%MSVC_TOOLSET%x"=="x" (
    echo MSVC_TOOLSET not found
) else (
    echo MSVC_TOOLSET %MSVC_TOOLSET%
    if "%MSVC_TOOLSET%"=="15" (
        set CMAKE_GENERATOR_PARAM=-G "Visual Studio 15 2017"
    )
    if "%MSVC_TOOLSET%"=="16" (
        set CMAKE_GENERATOR_PARAM=-G "Visual Studio 16 2019"
    )
    if "%MSVC_TOOLSET%"=="17" (
        set CMAKE_GENERATOR_PARAM=-G "Visual Studio 17 2022"
    )
)

@REM set CMAKE_GENERATOR_PARAM=-G Ninja
@REM set CMAKE_GENERATOR_PARAM=-G "NMake Makefiles"

set CMAKE_GENERATOR_PARAM=%CMAKE_GENERATOR_PARAM% -A Win32

echo=
echo CMAKE_GENERATOR_PARAM %CMAKE_GENERATOR_PARAM%

rmdir /q /s "%~dp0build-wxlua\x86"

@REM loop 5 times as wxlua project recommended.
SETLOCAL ENABLEDELAYEDEXPANSION
for %%i in (
    1
    2
    3
    4
    5
) do (
    set TK_CUSTOM_CONFIGURE_OPTS=
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DCMAKE_BUILD_TYPE=MinSizeRel
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DCMAKE_INSTALL_PREFIX="%~dp0build-wxlua\x86\install"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=FALSE
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DBUILD_SHARED_LIBS=TRUE -DBUILD_OUTPUT_DIRECTORY_ARCHIVE=lib -DBUILD_OUTPUT_DIRECTORY_LIBRARY=lib -DBUILD_OUTPUT_DIRECTORY_RUNTIME=bin
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxLuaBind_COMPONENTS="gl;stc;xrc;richtext;html;media;aui;adv;core;xml;net;base"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxLua_LUA_INCLUDE_DIR="%~dp0luajit-dist-win32\include"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxLua_LUA_LIBRARY="%~dp0luajit-dist-win32\lib\lua51.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxLua_LUA_LIBRARY_USE_BUILTIN=FALSE
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxWidgets_ROOT_DIR="%~dp0build-wxWidgets\x86"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxWidgets_LIB_DIR="%WXWIDGETS_LIBDIR%"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxWidgets_VERSION=%wxWidgets_VERSION%
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DwxWidgets_CONFIGURATION=mswu
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_adv="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_adv.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_aui="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_aui.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_base="%WXWIDGETS_LIBDIR%\wxbase%BUILD_VER_MMU%.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_core="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_core.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_gl="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_gl.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_html="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_html.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_media="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_media.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_net="%WXWIDGETS_LIBDIR%\wxbase%BUILD_VER_MMU%_net.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_propgrid="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_propgrid.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_qa="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_qa.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_ribbon="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_ribbon.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_richtext="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_richtext.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_stc="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_stc.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_webview="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_webview.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_xml="%WXWIDGETS_LIBDIR%\wxbase%BUILD_VER_MMU%_xml.lib"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_xrc="%WXWIDGETS_LIBDIR%\wx%BUILD_VER_MSWMMU%_xrc.lib"
    @REM set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_dbgrid=
    @REM set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_scintilla=
    @REM set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -DWX_odbc=
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -S "%~dp0wxlua-src\wxLua"
    set TK_CUSTOM_CONFIGURE_OPTS=!TK_CUSTOM_CONFIGURE_OPTS! -B "%~dp0build-wxlua\x86"

    echo TK_CUSTOM_CONFIGURE_OPTS !TK_CUSTOM_CONFIGURE_OPTS!

    cmake %CMAKE_GENERATOR_PARAM% !TK_CUSTOM_CONFIGURE_OPTS!
)
SETLOCAL DISABLEDELAYEDEXPANSION

@REM cmake --build build-wxlua\x86 --config "MinSizeRel"
@REM devenv build-wxlua\x86\wxLua.sln /Build "MinSizeRel|Win32"
@REM devenv build-wxlua\x86\wxLua.sln /Build "MinSizeRel|Win32" /project INSTALL
devenv build-wxlua\x86\modules\wxLuaModules.sln /Build "MinSizeRel|Win32"
devenv build-wxlua\x86\modules\wxLuaModules.sln /Build "MinSizeRel|Win32" /project INSTALL
